sonar.projectKey=apmantza_pi-lens
sonar.organization=apmantza

sonar.projectName=pi-lens
sonar.projectVersion=1.0

sonar.sources=clients,index.ts
sonar.tests=tests
sonar.exclusions=node_modules/**,rust/**,scripts/**,cases/**,**/*.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json

sonar.sourceEncoding=UTF-8
